name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, master]
  workflow_dispatch: # Allows manual triggering

jobs:
  claude-review:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: Customize the review behavior
          review_level: 'comprehensive' # Options: 'quick', 'standard', 'comprehensive'
          focus_areas: 'security,performance,maintainability,best-practices'
          # Optional: File patterns to include/exclude
          include_patterns: '**/*.{ts,tsx,js,jsx,py,java,go,rs,cpp,c,h}'
          exclude_patterns: '**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**'